include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/debian-build.gitlab-ci.yaml"

stages:
  - debian-build

debain-build:package:
  extends: .debain-build:common
  only:
    - feature/ci
