include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/cloudbuild-common.gitlab-ci.yaml"

stages:
  - cloudbuild

cloudbuild:package:
  extends: .cloudbuild:deb-package
  before_script:
    - cp contrib/relay.native.service contrib/service
    - wget -O contrib/global.config.json https://raw.githubusercontent.com/tonlabs/main.ton.dev/master/configs/ton-global.config.json
