[package]
name = "relay"
version = "0.1.0"
edition = "2018"
publish = false

[workspace]

members = [
    "relay-eth"
]
[dependencies]
base64 = "*"
config = { version = "*", default-features = false }
env_logger = "*"
failure = "*"
futures = "0.3.1"
log = "*"
tokio = { version = "0.2", features = ["full"] }
