[package]
name = "relay"
version = "0.1.0"
edition = "2018"
authors = ["Broxus team"]
publish = false
license-file = "LICENSE"

[workspace]
members = [
    "relay-eth",
    "client",
    "relay-ton",
    "relay-models"
]

[dependencies]
# Local dependencies
relay-eth = { path = "./relay-eth" }
relay-ton = { path = "./relay-ton" }
relay-models = { path = "./relay-models" }

# General dependencies
async-trait = "0.1"
anyhow = "1.0.33"
backtrace = "0.3.55"
base64 = "*"
bincode = "1.3.1"
chrono = { version = "0.4", features = ["serde"] }
clap = "3.0.0-beta.2"
config = { version = "*", features = ["yaml"] }
either = "1.6"
futures = "0.3.1"
hex = "0.4.2"
log = "*"
log4rs = "1.0.0"
num-bigint = "0.2.6"
num-traits = "0.2.14"
opg = {version =  "0.0", features =["chrono"] }
rand = "0.6"
sha3 = "0.9.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.59"
serde_yaml = "0.8.14"
sled = "0.34.5"
thiserror = "1.0.22"
toml = "0.5.7"
tokio = { version = "0.2", features = ["full"] }
url = "2.1.1"
warp = "0.2.5"

# ETH specific dependencies
ethereum-types = "0.9.2"
ethabi = "12.0.0"

# TON specific dependencies
ton_block = { git = "https://github.com/tonlabs/ton-labs-block.git" }
ton_abi = { git = "https://github.com/tonlabs/ton-labs-abi.git" }

# Crypto stuff
secp256k1 = { version = "0.19.0", features = ["default", "rand", "recovery"] }
ed25519-dalek = "1.0.1"
ring = "0.16.15"
sodiumoxide = "0.2.6"
secstr = "0.4.0"
tiny-hderive = "0.2.1"
tiny-bip39 = "0.8.0"

[dev-dependencies]
pretty_assertions = "0.6.1"

[features]
default = ["graphql-transport"]
tonlib-transport = ["relay-ton/tonlib-transport"]
graphql-transport = ["relay-ton/graphql-transport"]
paranoid = []

[package.metadata.deb]
depends = "$auto"
section = "utility"
assets = [
    ["target/release/relay", "usr/bin/relay", "755"],
    ["target/release/client", "usr/bin/relay-client", "755"],
]
conf-files = ["/etc/relay.conf"]
maintainer-scripts = "debian/"
[package.metadata.deb.systemd-units]
unit-scripts = "debian/"
