[package]
name = "relay"
version = "0.1.0"
edition = "2018"
authors = ["Broxus team"]
publish = false

[workspace]
members = [
    "relay-eth",
    "client",
    "relay-ton",
    "util"
]

[dependencies]
ethereum-types = "0.9.2"
relay-eth = { path = "./relay-eth" }
relay-ton = { path = "./relay-ton" }
url = "2.1.1"
base64 = "*"
anyhow = "1.0.33"
config = { version = "*", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.59"
rand = "0.6"
sha3 = "0.9.1"
hex = "0.4.2"
warp = "0.2.5"
#crypto stuff
secp256k1 = { version = "0.19.0", features = ["default", "rand"] }
ed25519-dalek = "1.0.1"
ring = "0.16.15"
sodiumoxide = "0.2.6"
secstr = "0.4.0"
tiny-hderive = "0.2.1"
tiny-bip39 = "0.8.0"
sled = "0.34.5"

clap = "3.0.0-beta.2"
log = "*"
env_logger = "*"
thiserror = "1.0.22"
futures = "0.3.1"
tokio = { version = "0.2", features = ["full"] }
daemonize = { version = "0.4.1", optional = true }
dialoguer = "0.7.1"

ton_block = { git = "https://github.com/tonlabs/ton-labs-block.git" }
ton_abi = { git = "https://github.com/tonlabs/ton-labs-abi.git", branch = "1.0.0-rc" }
num-bigint = "0.2.6" # fuck tonlabs
ethabi = "12.0.0"

[dev-dependencies]
pretty_assertions = "0.6.1"

[features]
default = ["graphql-transport"]
tonlib-transport = ["relay-ton/tonlib-transport"]
graphql-transport = ["relay-ton/graphql-transport"]
daemonizeable = ["daemonize"]

[package.metadata.deb]
depends = "$auto"
section = "utility"
priority = "optional"
copyright = "todo"
assets = [
    ["target/release/relay", "usr/bin/relay", "755"],
    ["target/release/client", "usr/bin/relay-client", "755"],
]
