[package]
name = "relay"
version = "0.1.0"
edition = "2018"
publish = false

[workspace]
members = [
    "relay-eth",
    "client"
    #    "enigma"
]
[dependencies]
relay-eth = { path = "./relay-eth" }
url = "2.1.1"
base64 = "*"
anyhow = "1.0.33"
config = { version = "*", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.59"
rand = "0.6"
sha3 = "0.9.1"
hex = "0.4.2"
warp = "0.2.5"
#crypto stuff
secp256k1 = { version = "0.19.0", features = ["default", "rand"] }
ring = "0.16.15"
sodiumoxide = "0.2.6"
secstr = "0.4.0"
tiny-hderive = "0.2.1"
tiny-bip39 = "0.8.0"
sled = "0.34.5"
warp-json-rpc = "0.2.0"

structopt = "0.3.20"
log = "*"
env_logger = "*"
#failure = "*"
futures = "0.3.1"
tokio = { version = "0.2", features = ["full"] }
daemonize = "0.4.1"
dialoguer = "0.7.1"

machine = "0.3.0"