[package]
name = "relay"
version = "2.0.0"
edition = "2018"
authors = ["Broxus team"]
publish = false
license-file = "LICENSE"

[dependencies]
async-trait = "0.1"
anyhow = "1.0"
chrono = "0.4.19"
clap = "3.0.0-beta.2"
config = { version = "0.11", default-features = false, features = ["yaml"] }
dashmap = "4.0"
external-ip = "4.1"
futures = "0.3"
hex = "0.4"
log = "0.4"
log4rs = "1.0"
num-bigint = "0.3"
once_cell = "1.8"
parking_lot = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
thiserror = "1.0"
tokio = { version = "1.6", features = ["sync", "fs", "rt-multi-thread", "macros"] }

# TON specific dependencies
ton_block = { git = "https://github.com/broxus/ton-labs-block" }
ton_abi = { git = "https://github.com/broxus/ton-labs-abi" }
ton_types = { git = "https://github.com/broxus/ton-labs-types" }

tiny-adnl = { git = "https://github.com/broxus/tiny-adnl" }

# Nekoton SDK
nekoton-abi = { git = "https://github.com/broxus/nekoton.git", features = ["derive"] }
nekoton-utils = { git = "https://github.com/broxus/nekoton.git" }

# Indexer engine
ton-indexer = { git = "https://github.com/broxus/ton-indexer.git", features = ["sha-native"] }

[dev-dependencies]
pretty_assertions = "0.7.2"

[package.metadata.deb]
depends = "$auto"
section = "utility"
assets = [
    ["target/release/relay", "usr/bin/relay", "755"],
    ["target/release/client", "usr/bin/relay-client", "755"],
]
conf-files = ["/etc/relay.conf"]
maintainer-scripts = "debian/"
features = ["graphql-transport", "tonlib-transport"]

[package.metadata.deb.systemd-units]
unit-scripts = "debian/"
