#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
  useradd bridge -r || true
  FILE=/etc/relay.conf
  if [ -f "$FILE" ]; then
    echo "$FILE exists."
    echo "If you want to generate default config run relay --gen-config"
  else
    echo "$FILE does not exist."
    echo "Generating default config"
    /usr/bin/relay --gen-config $FILE
  fi
  (mkdir "/var/lib/relay" && chown bridge:bridge -R "/var/lib/relay") || true
fi
#DEBHELPER#
